### ISSUE TITLE
Entschlackung

### ISSUE THREAD

**Issue by iPaat** [PHP-Fusion-GERMANY/PHP-Fusion#10]
Ich schlage vor dass wir den Core von seinen Features trennen.
- [x] Weblinks
- [ ] ~~News~~
- [ ] ~~Artikel~~
- [x] Downloads
- [x] FAQ
- [ ] ~~Eigene Seiten~~
- [x] Galerie
- [x] Forum
- [x] ...

Wir wandeln diese Features in Infusionen um.

**Edit**: Durchgestrichene Features bleiben im Core.

---

Ich denke wenn 4 Leute (mich ausgeschlossen) mit :+1: gestimmt haben, dann kann ich mich da ran setzen.

**Comment by Layzee0815** [comment]
Bin ich grundlegend dafür, allerdings finde ich, dass News, Artikel und eigene Seiten drinbleiben sollten, denn diese generieren den für Webseiten notwendigen Content. Auf der anderen Seite fände ichs wichtig, nicht mehr "news.php" standardmässig als Startseite zu setzen sondern da ggf was eigenes zu basteln, damit der User die Möglichkeit hat, die Startseite ohne codetechnischen Aufwand selbst zu gestalten. Die Newssektion sollte als eigene Sektion (wie auch Downloads, Artikel und co) im System hinterlegt werden.

**Comment by iPaat** [comment]
Also ich finde wenn dann sollten wir uns auf **EINS** einigen.

### News

Wenn es nur News gibt, dann ist das ganze mit einem Blog vergleichbar. Wäre ganz nett für Anfänger da sie einfach eine Seite aufsetzen können und dann i.was da schreiben können.

### Artikel

Ähnlich wie News. Ich würde aber die News den Artikeln vorziehen.

### Eigene Seiten

Um mit Eigenen Seiten vernünftigen Content zu generieren, sind schon erweiterte Kenntnisse erforderlich wie ich finde. Daher fallen diese für mich, als einzig aktiviertes Feature, flach.

**Comment by Webmeteor** [comment]
Ich bin dafür alles, was im Root rum liegt (Ausnahme index.php und maincore.php) in die Infusions wandern zu lassen.
Nicht jeder benötigt auch die Registrierung.
Beim Kontaktformular geben wir so die Möglichkeit zu eigenen Infusionen für angepasste Formulare.

@SuNflOw1991 die eigenen Seiten benötige ich für einfache Internetseiten. Also benötigt werden diese. Können aber wie gesagt als Infusion.

Als Startseite könnte man den Infusionsordner nach Panels suchen lassen, die man dann auswählen kann. Ähnlich des einen Themes aus der V9, wo das dann eben Widgets heisst.
Oder eigene Widgets nur für die Startseite, die man ein und ausschalten kann.

Es sollten aber dennoch alle jetzigen Funktionen, die Fusion bietet verfügbar bleiben.

**Comment by GUL-Sonic** [comment]
> Bin ich grundlegend dafür, allerdings finde ich, dass News, Artikel und eigene Seiten drinbleiben sollten.

Dem Schließe ich mich an

**Comment by GUL-Sonic** [comment]
> News
> Wenn es nur News gibt, dann ist das ganze mit einem **Blog** vergleichbar. Wäre ganz nett für Anfänger da sie einfach eine Seite aufsetzen können und dann i.was da schreiben können.

Ein Blogsystem könnte extra erstellt werden, um auch den Upload und das Einfügen von Bildern zu ermöglichen kleines Beispiel: http://www.burnout-zeit-für-veränderungen.de/infusions/knb_blog_panel/blog.php

> Eigene Seiten
> Um mit Eigenen Seiten vernünftigen Content zu generieren, sind schon erweiterte Kenntnisse erforderlich wie ich finde. Daher fallen diese für mich, als einzig aktiviertes Feature, flach.

Sind für Anfänger sehr Interessant, da hier mit wenig Kenntnissen erste Schritte zur Gestaltung und zum Aufbau einer Seite mit Tabellen, Bildern, Links und erste Codierungen erlernt werden können.
Von daher würde ich sie auch drinnen lassen. (so habe ich mal angefangen ^.^)

**Comment by Layzee0815** [comment]
Man kann für eigene Seiten auch den Tiny oder CKEditor zur Verfügung stellen um Content zu generieren. Wir dürfen nur nicht dazu neigen, immer vom eigenen Wissensstand auszugehen.

Ein absoluter Neuling, der Fusion zum ersten Mal installiert, wird sich erst einmal umschauen wollen. Findet er dann im Grundsystem keine Möglichkeit EIGENEN Content zu erstellen verliert er schnell die Lust. Selbst wenn man am Anfang bei der Installation schon wählen kann, neue User können mit Begrifflichkeiten Wie "Newssystem", "Artikelsystem" usw wohl eher wenig anfangen. Das heisst sie verstehen sicherlich was damit gemeint ist aber die Frage ob sie diese Module brauchen können sie an diesem Punkt nicht beantworten.

Wie gesagt, ich bin dafür dass Dinge wie Forum, Weblinks, FAQ und ähnlicher Kram als Infusion angehängt oder angeboten werden, aber die grundlegenden Systeme zum generieren von Content sollten Bestandteil des Cores bleiben.

**Comment by iPaat** [comment]
Okay, was ich daraus erkennen kann ist, dass 
- News
- Artikel
- EIgene Seiten

erhalten bleiben sollen. Ich habe meinen Eingangspost überarbeitet und warte jetzt auf den 4. Vote :+1:
