### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by iPaat** [PHP-Fusion-GERMANY/PHP-Fusion#13]
Da wir mit #10 den Core entschlackt haben, müssen wir den Downloadbereich als Infusion realisieren. Ich möchte hier Vorschläge sammeln wie der Downloadbereich in Zukunft gestaltet werden soll.

**Comment by Webmeteor** [comment]
Ich würde einfach nur das Design vom Code trennen, den Rest werden dann andere Entwickler als Infusionen bereitstellen. Der Community Gedanke darf ja nicht ausser acht gelassen werden.

Also nur eine Fallback render_download() Funktion.
Nur muss dafür ja erst einmal einiges im Core fertig sein, wie DB und URL-Rewriting
