### ISSUE TITLE
Modernisierung Core

### ISSUE THREAD

**Issue by iPaat** [PHP-Fusion-GERMANY/PHP-Fusion#14]
Hier würde ich gerne alle Ideen zur Modernisierung sammeln. Bevor wir nämlich Dinge umschreiben müssen wir erst einmal wissen was wir modernisieren wollen.
## Vorschläge
- [x] Neue Datenbankanbindung ( #8 )
- [ ] SEF/SEO
- [ ] Formularsystem
- [x] Bootstrap integrieren (und im Core nutzen) ( #17 , #22  )

**Comment by Webmeteor** [comment]
Als erstes brauchen wir überarbeitete Datenbankfunktionen.
Dann muss das URL-Rewriting fertig sein.
Funktionen zum Überprüfen von Usereingaben.

Das sind glaube ich die Hauptsächlichen Dinge, bevor wir uns um anderes Kümmern können / sollten.
Aus diesen 3 Dingen ergeben sich garantiert auch noch andere Dinge zwangsläufig, die geändert werden müssen.

**Comment by iPaat** [comment]
Sollen wir [Bootstrap](http://getbootstrap.com/) fest integrieren?

Ich finde schon richtig dass wir auf ein CSS Framework zurückgreifen. Vielleicht laden wir nicht immer automatisch die CSS und Scripte dazu aber! wenigstens die Klassen sollten wir in den Core übernehmen damit man mehr gestalten kann und wenn man will kann man sich dann auch Designs kaufen die dann auf PHP-Fusion laufen bzw. nicht so schwer zu portieren sind.

**Comment by Webmeteor** [comment]
Da mittlerweile fast alle Designer auf Bootstrap setzen, sollte es integriert werden. Und da Bootstrap für Anfänger ähnlich einfach ist, wie Tabellenlayouts. Würde dabei aber eher auf MaxCDN setzen.

FontAwesome sollte man vielleicht auch als Option integrieren.

Formularsystem, wie weit würdest du da gehen, ähnlich wie in der V9 der defender?

**Comment by iPaat** [comment]
Also ich finde die IDEE hinter Defender echt nicht schlecht. Nur wir sollten aus den Fehlern die, die Engländer gemacht haben lernen.

**Comment by Webmeteor** [comment]
Die Idee ist super, nur die Ausführung schlecht, bzw. hat ab und an unerklärliche Nebenwirkungen.

Die Formularfelder haben auch noch einen ungünstigen Nebeneffekt, will man alle Eventualitäten berücksichtigen, ist entweder der Code aufgebläht oder der Seitenquelltext.

Eine einfache Überprüfungsfunktion, wie sie damals im RapidCMS Projekt (sollten ja fast noch alle kennen, ansonsten das Codefragment habe ich noch) eingebaut war, würde glaube ich schon reichen.
Was die UK's schön gelöst haben ist der Multiupload. Damit haben nun auch Anfänger es etwas leichter vor allem den Bilderupload zu integrieren.

**Comment by Rolly8-HL** [comment]
Wo kann ich mir das laden zum testen, was da schon geändert wurde.
Kann da so nichts zu beitragen, arbeite gerade mit V7 PHP7 und veränderter 
DB_SUBMISSIONS und DB_SUBMISSIONS_ADD um auch anderen Codern die Möglichkeit zu geben über Einsenden.

**Comment by Webmeteor** [comment]
Noch ist nichts wirklich geändert. Ansonsten ist oben Rechts ein Button für den Download hier auf Github.

**Comment by Rolly8-HL** [comment]
> Button für den Download 

Habe ich ja gemacht aber die läuft nicht unter PHP7.
Arbeite mit der (Nicht offizielle PHP Fusion Version 7.02.07 PDO PHP7) leicht abgeändert, mit automatischer Erkennung für PDO.
Kann unter PHPv.5.xx installieren und danach auf PHPv.7 den Server umstellen ohne Probleme.

**Comment by globeFrEak** [comment]
Wie oder wo kann ich helfen?!
Wie machen wir weiter?

**Comment by iPaat** [comment]
Du könntest PDO einbauen ( #8 ).
In #8 sind schon mal die Funktionen was fehlt habe ich schon mal kommentiert. Du kannst dann einen PR gegen  [`webmeteor:patch-2`](https://github.com/Webmeteor/PHP-Fusion/tree/patch-2) machen. Dann können wir da schon einmal weiter machen und müssen nicht warten. Natürlich habe ich den Code noch nicht getestet.

**Comment by globeFrEak** [comment]
OK, ich wusste jetzt nicht genau wie ich es mit Github anstelle.
Ich habe mir einen neuen Branch in meinem Repo gemacht?
https://github.com/globeFrEak/PHP-Fusion/tree/Enhancement/PDO
- [X] 1. Dateiendung fehlt
- [X] 2. Diese Datei wird an keiner Stelle verwendet
- [X] 2A. Alte DB Funktionen aus Maincore löschen
- [X] 3. Bitte überprüfe die Benennung deiner Branches (mit Prefix: Feature-, Enhancement-, Fix-)
- [x] 4. PHPDoc fehlt
- [x] 5. PDO wird Exceptions werfen die nicht aufgefangen werden

zum Thema PHPDoc und PDO Exceptions habe ich keine große Erfahrung

**Comment by iPaat** [comment]
Vielen Dank, dann machst du einfach einen PR von da aus. Das sollte auch okay sein.

---

PHPDoc einfach einfügen:
- [Parameter](https://www.phpdoc.org/docs/latest/references/phpdoc/tags/param.html)
- [Return](https://www.phpdoc.org/docs/latest/references/phpdoc/tags/return.html)

PDO Ecxeptions kannst du erst mal so lassen. Wir würden dann am besten später die PDO Exceptions mit in das Error Log schreiben.
