### ISSUE TITLE
Update Skript

### ISSUE THREAD

**Issue by iPaat** [PHP-Fusion-GERMANY/PHP-Fusion#18]
Wir müssen früher oder später ein Update Skript für die Datenbank schreiben welches die Daten aus der Datenbank löscht oder Migriert. Bitter hier alle Änderungen an der Datenbank dokumentieren damit man später dann das Update Skript schreiben kann.

**Comment by iPaat** [comment]
- [ ] In #11 und #15 sind mehrere Tabellen gelöscht worden.
- [ ] Außerdem müssen die Rechte der Administratoren in der User Tabelle korrigiert werden.
- [ ] Links zu den nicht mehr existenten Features müssen aus der Navigation entfernt werden.
- [ ] In der Admin Tabelle müssen die Einträge entfernt werden
- [ ] Aus der Kommentar und Rating Tabelle müssen Kommentare zu Downloads und Photos entfernt werden

**Comment by iPaat** [comment]
-  [ ] In #17 wurden die Einstellungen erweitert:

``` sql
INSERT INTO fusionPrefix_settings 
  (settings_name, settings_value) 
VALUES 
('jquery_url', '//code.jquery.com/jquery-1.12.4.min.js'),
('jquery_sri', 'sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ'),
('font_url', '//maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css'),
('font_sri', 'sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1'),
('bootstrap_css_url', '//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css'),
('bootstrap_css_sri', 'sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7'),
('bootstrap_js_url', '//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js'),
('bootstrap_js_sri', 'sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS');
```

**Comment by Webmeteor** [comment]
Die in #11  und #15 dürfen bei einem Update auf keinen Fall einfach gelöscht werden. Damit würden wir ja auch die Inhalte gelöscht werden. Genauso dürfen die Links nicht aus der Navigation gelöscht werden, hier müssen die Links umgeschrieben werden.
Und auch den rest kannst du nicht einfach entfernen. Kann ja keiner mehr sein Fotoalbum bedienen oder die Umfragen. Und Kommentare dürfen wir auch nicht einfach löschen (ist eh unnötig, wenn beides nicht genutzt wird, dann sind auch keine Einträge da.

Du würdest mit deinem Update Script bei vielen Usern fast alle Inhalte ungefragt löschen.

Wir müssen im Update auf jedenfall den UTF-8 Support herstellen für die Datenbank.

**Comment by iPaat** [comment]
Guter Einwand!

Wir könnten den User ja ein Backup anbieten welches er vorher machen soll. Später dann wenn es Infusionen gibt zu den Teilen die wir entfernt haben, muss es auch ein Migrationskript geben, welches es dann erlaubt die alten Backups in das neue Schema zu integrieren.
