### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by iPaat** [PHP-Fusion-GERMANY/PHP-Fusion#3]
Ich habe das Repository entsprechen vorbereitet. Was uns nun fehlt ist eine tolle Readme die unsere Projekt beschreibt usw.

Dies würde ich gerne Layzee machen lassen da er eine tolle Ausdrucksweise hat.

**Comment by Layzee0815** [comment]
Komme ich heute nicht mehr zu, setz ich mich aber gerne ran sobald ich Zeit habe.

**Comment by SGIFusion** [comment]
Bin ich auch für er hat eine Spitzen ausdrucksweise (wo ich gerne eine scheibe von abschneiden würde) ;)

**Comment by Layzee0815** [comment]
[ReadMe.txt](https://github.com/PHP-Fusion-GERMANY/PHP-Fusion/files/313228/ReadMe.txt)

**Comment by Webmeteor** [comment]
Ist sehr gut. Sollten wir die Österreicher nicht mit erwähnen? Oder besser deutschsprachiger Raum, das würde die Schweizer mit einbeziehen.

**Comment by Layzee0815** [comment]
Naja... die Österreicher beteiligen sich bisher nicht daran... ich habe es jetzt trotzdem mal geändert in "deutschprachiger Raum"...
UPDATE:
[ReadMe.txt](https://github.com/PHP-Fusion-GERMANY/PHP-Fusion/files/313287/ReadMe.txt)

**Comment by iPaat** [comment]
Vielen Dank :+1: 
Ich würde dich bitten, damit auch sichtbar ist dass dies von dir kommt, einen Pull Request zu senden mit der Datei `README.md` (Schreibweise ist wichtig!). Um diese dann noch schön zu gestellten kannst du [Markdown](https://guides.github.com/features/mastering-markdown/) benutzen.

**Comment by Layzee0815** [comment]
Um ehrlich zu sein ist mir völlig Latte ob jemand sieht dass es von mir kommt.
Es geht hier nicht um die "Leistungen" Einzelner sondern um das Erreichen gesteckter Ziel als TEAM.
Ich brauche nicht auf jedem Mist der von mir kommt meinen Stempel ;)

Ich muss mir das Ganze erst noch in Ruhe anschauen und kann dir nicht sagen wann ich wirklich mal dazu komme. Ich arbeite, wie sicher einige von euch wissen neben der IT auch im Support für gleich mehrere Unternehmen und momentan fehlt mir schlicht die Zeit und Ruhe dafür.

Du darfst also, da es ja drängt, den Text aus der ReadMe gerne so übernehmen und das Ding als Request einstellen... auch ohne meinen Namen ;)
