### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by iPaat** [PHP-Fusion-GERMANY/PHP-Fusion#4]
Wir benötigen Richtlinien an die sich jeder Entwickler halten muss. Diese enthalten:
- CodingStyle
- Sprachen (Quellcode IMMER Englisch)
- Templates für Pull Requests und Fehler Meldungen
- OOP oder Funktional
- Benennungen von Branches und Commits 
- ...

Diese Datei heißt CONTRIBUTE.md und sollte in ein Verzeichnis .github gepackt werden.

**Comment by Webmeteor** [comment]
OOP sollte wirklich so wenig wie möglich genutzt werden. Ich denke das KISS Prinzip sollte weiter geführt werden, damit auch PHP Anfänger schnell zu erfolgen kommen und uns der Nachwuchs nicht ausgeht. Denn das ist ja das was Fusion auszeichnet.
OOP wirklich nur da, wo kein Entwickler und Designer etwas zu verändern hat.

Den CodingStyle können (müssen) wir ja von den Engländern übernehmen. [https://php-fusion.co.uk/infusions/wiki/documentation.php?page=209](https://php-fusion.co.uk/infusions/wiki/documentation.php?page=209)
Vorsicht ist schon für die V9 dort.

**Comment by iPaat** [comment]
Ich stimme @Webmeteor zu. Um das CMS weiter einfach zu halten sollten wir nicht auf [OOP](https://de.wikipedia.org/wiki/Objektorientierte_Programmierung) zurückgreifen.

Was Coding Style angeht müssten wir dann das entsprechende Dokument übersetzen.

**Comment by Layzee0815** [comment]
Bitte auf KEINEN Fall OOP wenn es vermeidbar ist. Bitte UNBEDINGT Nicks "KISS"-Prinzip als Grundlage bei allen Entwicklungen im Fokus behalten!

**Comment by Webmeteor** [comment]
Was man machen könnte ist ein Pseudo OOP. So kann man die autoload Funktion von PHP Klassen auch für zusammengetragene Funktionen in einer Datei nutzen.

Ala

```
class dbpdo{
}
function dbconnect(){
usw.
```

einbinden kann man das dann mit
new dbpdo;
Und hat so die Funktionen eingebunden anstelle eines includes

**Comment by globeFrEak** [comment]
Wir sollten uns auch auf ein Copyright "Template" der von uns modifizierten/erstellen Dateien einigen.
Dabei würde ich den originalen Copyright unangetastet lassen und unseren darunter setzen?!
