### ISSUE TITLE
Profilbild

### ISSUE THREAD

**Issue by iPaat** [PHP-Fusion-GERMANY/PHP-Fusion#5]
Es wäre schön wenn jemand ein 420x420 Pixel großes Bild entwerfen könnte welches das Projekt widerspiegelt.

PHP-Fusion sollte schon i.wie erkennbar sein.

**Comment by Layzee0815** [comment]
Kümmere ich mich drum sobald ich dazu komme.

**Comment by Layzee0815** [comment]
Mal so als Beispiel-Entwurf:
![ava1](https://cloud.githubusercontent.com/assets/19905680/16007710/70d2bb6e-3174-11e6-9850-f546aecbd0aa.jpg)

**Comment by iPaat** [comment]
Vielen Dank für deinen Entwurf. :+1: 

Da GitHub das Bild leider in vielen Bereichen herunter skaliert 
![beispiel](https://cloud.githubusercontent.com/assets/943484/16011133/76579eaa-3184-11e6-8652-75dbd416c6d3.png)
An manchen Stellen ist es nicht mehr als in diesem Screen zu sehen.

**Comment by Layzee0815** [comment]
Hmm... warum dann 420x420 Pixel?
Ich werd was Neues basteln...

**Comment by iPaat** [comment]
Das habe ich mich auch gefragt. Aber der Link zum aktuellen Bild ist dieser:
https://avatars0.githubusercontent.com/u/19901863?v=3&s=420&u=ccbcc5fbc5a372535bce63270f148fcc46c8ef83

**Comment by SGIFusion** [comment]
Verwirrrend aber was soll man machen wenn git diese Vorgaben brauch :o

**Comment by Layzee0815** [comment]
Und sowas hier?
![fusion7](https://cloud.githubusercontent.com/assets/19905680/16018652/abd7ad74-31a5-11e6-929b-9fd16f9a0c5d.png)

**Comment by iPaat** [comment]
Hab es eingestellt. Danke :+1:
