### ISSUE TITLE
Verantwortlichkeiten

### ISSUE THREAD

**Issue by iPaat** [PHP-Fusion-GERMANY/PHP-Fusion#6]
Da ich nicht alleine für alles verantwortlich sein kann (und will) würde ich gerne Verantwortlichkeiten abgeben.

Da ich nicht jeden kenne, würde ich euch bitten hier eine kleine CV ([Beschreibung was das ist hier](https://tabellarischer-lebenslauf.net/faq/curriculum-vitae-cv/)) zu verfassen. Gerne könnt ihr mir Arbeitsproben per [conrad.patrick.1@gmail.com](E-Mail) zukommen lassen oder auf GitHub hochladen.

Interessant sind Informationen wie:
- Projekte auf welchen Niveau
- Wie lange wird schon Programmiert (auch andere Sprachen)
- Erfahrung mit Teamarbeit
- Erfahrung mit git und GitHub

Ich mache dies einfach um euch besser einzuschätzen. Ich bezweifele nicht dass ihr Programmieren könnt. Nur z.B. die Mitglieder des @PHP-Fusion-GERMANY/prufung s Team müssen nicht nur programmieren können sondern auch ein Auge auf Details haben. Eventuelle Fehler, Sicherheitslücken etc. erkennen und auch kommunizieren können.

Ich würde ungern jedem blind Schreibrechte auf das Repo geben. Vor allem habe ich die Erfahrung gemacht dass dies bei git Anfängern fatal sein kann. Ich würde aber gerne demokratisch entscheiden lassen wer wie weit Zugriff haben soll. Dazu dann nach den [CV](https://tabellarischer-lebenslauf.net/faq/curriculum-vitae-cv/)s mehr

**Comment by Webmeteor** [comment]
In eine FAQ können wir keine Daten eingeben. Hast du zufällig falsche Links?

Meine Arbeiten kennst du ja, und Giterfahrung bin gerade erst am Sammeln.

**Comment by Layzee0815** [comment]
Git nutze ich offen gestanden jetzt zum zweiten Mal und muss mir da auch erstmal einen Überblick verschaffen. Allerdings stelle ich mich natürlich gerne als "Aufsichtsratvorsitzender" und "Überwacher vom Dienst" zur Verfügung. Kennen solltet ihr mich inzwischen alle und auch meine Arbeiten.

Natürlich code ich auch gerne mit, allerdings sind meine Zeitfenster immer sehr klein für das Hobby PHP-Fusion, deshalb dürft ihr in dem Bereich bitte nicht zuviel von mir erwarten.

**Comment by SGIFusion** [comment]
Ich muss mich erst einmal komplett hier reinfuchsen und in solch einem Projekt wäre ich nun zum ersten mal aber bin durch dieverse Seiten als Benutzer oder höher bekannt (Positiv oder auch Negativ Shit happens :P) ansonsten bin ich gerne für neue Lernfelder offen und was meine zeiten angeht ist es immer verschieden ;)

**Comment by iPaat** [comment]
Vielen Dank,
ich würde dann sagen dass wir abstimmen ob ich @Layzee0815 ebenfalls zum [Owner](https://help.github.com/articles/permission-levels-for-an-organization/) des Projekts machen soll.

Abstimmen könnt ihr indem ihr oben in @Layzee0815s Beitrag auf das +SMILEY Symbol drückt und dort den Daumen hoch auswählt.

**AbstimmungsENDE**: 16.06.2016

**Comment by GUL-Sonic** [comment]
Hi,
erst einmal danke dafür, dass Ihr mich mit ins Boot geholt habt.
Erfahrungen mit github habe ich dank globefreak und unserem Projekt clancash-panel. Programmiererfahrungen habe ich durch die Infusions und Panels die ich zum Teil "überarbeitet" zum Teil selbst geschrieben habe. Alles was ich über php, css, html weiß, habe ich mir selbst beigebracht oder dank Forenunterstützung gelernt, beruflich bin ich jedoch 100% branchenfremd. Zeit ist wie bei fast allen von Euch denke ich relativ. Nebst Familie und weiteren Verpflichtungen nehme ich mir gerne die Zeit die es braucht um Euch tatkräftig zu unterstützen.

Kurz gesagt: Mitentwickeln ja sehr gerne, Schreibrechte bzw. Fehlerprüfung und Absegnung von Erweiterungen eher nicht, das sollten wirklich nur die Profis unter uns / euch  machen.

**Comment by iPaat** [comment]
Da sich alle dafür ausgesprochen haben, werde ich @Layzee0815 zum Owner machen.
